# Generated by Django 5.1.1 on 2026-07-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('account_id', models.CharField(max_length=255)),
                ('group_jid', models.CharField(max_length=255)),
                ('message_id', models.CharField(max_length=255)),
                ('group_name', models.CharField(blank=True, max_length=255)),
                ('sender_id', models.CharField(blank=True, max_length=255)),
                ('sender_e164', models.CharField(blank=True, max_length=255)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('body', models.TextField(blank=True, default='')),
                ('message_type', models.CharField(blank=True, max_length=255)),
                ('media_type', models.CharField(blank=True, max_length=255)),
                ('media_path', models.TextField(blank=True, default='')),
                ('gated_out', models.BooleanField(default=False)),
                ('would_process_agent', models.BooleanField(default=False)),
                ('skip_reason', models.CharField(blank=True, max_length=255)),
                ('raw_json', models.JSONField(default=dict)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('account_id', 'group_jid', 'message_id'), name='forestal_bot_whatsapp_message_identity_uniq')],
            },
        ),
    ]
