# Generated by Django 5.1.1 on 2026-07-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestal_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['timestamp', 'created_at'], name='forestal_wa_ts_created_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['group_jid', 'timestamp', 'created_at'], name='forestal_wa_group_ts_cr_idx'),
        ),
    ]
