# Generated by Django 5.1.1 on 2026-07-10 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestal_bot', '0002_whatsappmessage_forestal_wa_ts_created_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255)),
                ('jid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'jid'],
                'indexes': [models.Index(fields=['jid'], name='forestal_wag_jid_idx'), models.Index(fields=['account_id', 'active'], name='forestal_wag_acct_active_idx'), models.Index(fields=['name'], name='forestal_wag_name_idx')],
                'constraints': [models.UniqueConstraint(fields=('account_id', 'jid'), name='forestal_bot_whatsapp_group_identity_uniq')],
            },
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='forestal_bot.whatsappgroup'),
        ),
    ]
