# Generated by Django 5.1.1 on 2026-07-10 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestal_bot', '0004_backfill_whatsapp_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='transcribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='transcription',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)]),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='transcription_error',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='transcription_status',
            field=models.CharField(blank=True, choices=[('', 'Sin estado'), ('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completada'), ('failed', 'Fallida')], default='', max_length=32),
        ),
    ]
