# Generated by Django 5.1.1 on 2026-07-10 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestal_bot', '0005_whatsappmessage_transcribed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='image_analysis_error',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='image_analysis_status',
            field=models.CharField(blank=True, choices=[('', 'Sin estado'), ('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completada'), ('failed', 'Fallida')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='image_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='image_description',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(10000)]),
        ),
    ]
