# Generated by Django 5.1.1 on 2026-07-13 17:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestal_bot', '0006_whatsappmessage_image_analysis_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummaryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('operational_date', models.DateField(db_index=True)),
                ('generated_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('generated', 'Generado'), ('partial', 'Entrega parcial'), ('sent', 'Enviado'), ('failed', 'Fallido')], max_length=16)),
                ('consolidated_text', models.TextField(validators=[django.core.validators.MaxLengthValidator(50000)])),
                ('spoken_script', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(50000)])),
                ('total_groups', models.PositiveIntegerField(default=0)),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('generator_version', models.CharField(blank=True, default='', max_length=100)),
                ('source', models.CharField(default='openclaw', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-operational_date', '-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DailySummaryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_key', models.CharField(max_length=100)),
                ('group_name', models.CharField(max_length=255)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('summary_text', models.TextField(validators=[django.core.validators.MaxLengthValidator(30000)])),
                ('no_updates', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='forestal_bot.dailysummaryrun')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('run', 'group_key'), name='forestal_bot_daily_summary_group_uniq')],
            },
        ),
        migrations.CreateModel(
            name='DailySummaryDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=32)),
                ('recipient_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('skipped_duplicate', 'Duplicado omitido')], max_length=32)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('external_id', models.CharField(blank=True, default='', max_length=255)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='forestal_bot.dailysummaryrun')),
            ],
            options={
                'ordering': ['channel', 'recipient_name'],
                'constraints': [models.UniqueConstraint(fields=('run', 'channel', 'recipient_name'), name='forestal_bot_daily_summary_delivery_uniq')],
            },
        ),
    ]
