# Generated by Django 5.1.1 on 2026-07-19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("forestal_bot", "0007_dailysummaryrun_dailysummarygroup_and_more")]

    operations = [
        migrations.CreateModel(
            name="WeighingMovement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("organization_key", models.CharField(db_index=True, default="forestal-paraguay", max_length=64)),
                ("origin_group_key", models.CharField(db_index=True, default="logistica-felber", max_length=100)),
                ("operational_date", models.DateField(db_index=True)),
                ("plate_normalized", models.CharField(blank=True, db_index=True, default="", max_length=32)),
                ("plate_original", models.CharField(blank=True, default="", max_length=64)),
                ("driver_name", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("status", models.CharField(choices=[("pendiente", "Pendiente"), ("completo", "Completo"), ("observado", "Observado"), ("anulado", "Anulado")], db_index=True, default="pendiente", max_length=16)),
                ("declared_quantity_kg", models.PositiveIntegerField(blank=True, null=True)),
                ("official_scale", models.CharField(blank=True, choices=[("felber", "Felber"), ("forestal_paraguay", "Forestal Paraguay"), ("otro", "Otro")], max_length=32, null=True)),
                ("observations", models.TextField(blank=True, default="")),
                ("evidence", models.JSONField(blank=True, default=list)),
                ("source_message_ids", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-operational_date", "-created_at"]},
        ),
        migrations.CreateModel(
            name="WeighingMeasurement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("scale", models.CharField(choices=[("felber", "Felber"), ("forestal_paraguay", "Forestal Paraguay"), ("otro", "Otro")], max_length=32)),
                ("kind", models.CharField(choices=[("tara", "Tara"), ("bruto", "Bruto")], max_length=16)),
                ("weight_kg", models.PositiveIntegerField()),
                ("source", models.CharField(choices=[("foto_balanza", "Foto de balanza"), ("remision", "Remisión"), ("planilla", "Planilla"), ("mensaje", "Mensaje"), ("correccion_manual", "Corrección manual")], max_length=32)),
                ("evidence_id", models.CharField(blank=True, default="", max_length=255)),
                ("message_id", models.CharField(blank=True, default="", max_length=255)),
                ("measured_at", models.DateTimeField()),
                ("correction_reason", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("movement", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="measurements", to="forestal_bot.weighingmovement")),
            ],
            options={"ordering": ["scale", "kind"]},
        ),
        migrations.CreateModel(
            name="WeighingMeasurementRevision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("revision", models.PositiveIntegerField()),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("weight_kg", models.PositiveIntegerField()),
                ("source", models.CharField(choices=[("foto_balanza", "Foto de balanza"), ("remision", "Remisión"), ("planilla", "Planilla"), ("mensaje", "Mensaje"), ("correccion_manual", "Corrección manual")], max_length=32)),
                ("evidence_id", models.CharField(blank=True, default="", max_length=255)),
                ("message_id", models.CharField(blank=True, default="", max_length=255)),
                ("measured_at", models.DateTimeField()),
                ("correction_reason", models.CharField(blank=True, default="", max_length=500)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("measurement", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="revisions", to="forestal_bot.weighingmeasurement")),
            ],
            options={"ordering": ["revision"]},
        ),
        migrations.AddIndex(
            model_name="weighingmovement",
            index=models.Index(fields=["organization_key", "operational_date"], name="forestal_weigh_org_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="weighingmeasurement",
            constraint=models.UniqueConstraint(fields=("movement", "scale", "kind"), name="forestal_weigh_measurement_identity_uniq"),
        ),
        migrations.AddConstraint(
            model_name="weighingmeasurementrevision",
            constraint=models.UniqueConstraint(fields=("measurement", "revision"), name="forestal_weigh_revision_identity_uniq"),
        ),
    ]
