# Generated by Django 5.1.1 on 2026-07-20 21:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestal_bot', '0008_weighing_movements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FgpyDriver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_key', models.CharField(db_index=True, default='forestal-paraguay', max_length=64)),
                ('reported_name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('external_identifier', models.CharField(blank=True, default='', max_length=128)),
                ('proposal_key', models.CharField(blank=True, default='', max_length=128)),
                ('whatsapp_sender_identifier_hash', models.CharField(blank=True, default='', max_length=64)),
                ('confirmed_aliases', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('inactive', 'Inactivo')], db_index=True, default='pending', max_length=16)),
                ('created_via', models.CharField(choices=[('bot', 'Bot'), ('user', 'Usuario')], max_length=8)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_fgpy_drivers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fgpy_drivers', to=settings.AUTH_USER_MODEL)),
                ('initial_source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposed_fgpy_drivers', to='forestal_bot.whatsappmessage')),
            ],
            options={
                'db_table': 'forestal_bot_fgpy_driver',
                'ordering': ['reported_name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FgpyVehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_key', models.CharField(db_index=True, default='forestal-paraguay', max_length=64)),
                ('original_plate', models.CharField(blank=True, default='', max_length=64)),
                ('normalized_plate', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('internal_code', models.CharField(blank=True, default='', max_length=64)),
                ('proposal_key', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('make', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('confirmed_aliases', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('inactive', 'Inactivo')], db_index=True, default='pending', max_length=16)),
                ('created_via', models.CharField(choices=[('bot', 'Bot'), ('user', 'Usuario')], max_length=8)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_fgpy_vehicles', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fgpy_vehicles', to=settings.AUTH_USER_MODEL)),
                ('initial_source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposed_fgpy_vehicles', to='forestal_bot.whatsappmessage')),
            ],
            options={
                'db_table': 'forestal_bot_fgpy_vehicle',
                'ordering': ['description', 'original_plate', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_key', models.CharField(db_index=True, max_length=64)),
                ('origin_group_key', models.CharField(db_index=True, max_length=100)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('event_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('liters', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('odometer_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('odometer_partial', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('station', models.CharField(blank=True, default='', max_length=255)),
                ('receipt_number', models.CharField(blank=True, default='', max_length=100)),
                ('fuel_type', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('received', 'Recibida'), ('requires_review', 'Requiere revisión'), ('confirmed', 'Confirmada'), ('corrected', 'Corregida'), ('rejected', 'Rechazada')], db_index=True, default='received', max_length=24)),
                ('overall_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('field_confidence', models.JSONField(blank=True, default=dict)),
                ('original_extraction', models.JSONField(blank=True, default=dict)),
                ('inconsistencies', models.JSONField(blank=True, default=list)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forestal_bot_fuel_reports', to='forestal_bot.fgpydriver')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_forestal_bot_fuel_reports', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forestal_bot_fuel_reports', to='forestal_bot.fgpyvehicle')),
            ],
            options={
                'db_table': 'forestal_bot_fuel_report',
                'ordering': ['-event_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelReportEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('receipt', 'Comprobante'), ('dashboard', 'Tablero'), ('combined', 'Combinada'), ('other', 'Otra')], max_length=16)),
                ('file', models.FileField(upload_to='forestal_bot/fuel/%Y/%m/')),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('position', models.PositiveIntegerField(default=0)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='forestal_bot.fuelreport')),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuel_evidence_files', to='forestal_bot.whatsappmessage')),
            ],
            options={
                'db_table': 'forestal_bot_fuel_report_evidence',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FuelReportRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=64)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('correction_source', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='forestal_bot.fuelreport')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forestal_bot_fuel_report_revision',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FuelReportSourceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('initial', 'Inicial'), ('receipt', 'Comprobante'), ('dashboard', 'Tablero'), ('clarification', 'Aclaración'), ('correction', 'Corrección'), ('confirmation', 'Confirmación')], max_length=24)),
                ('position', models.PositiveIntegerField(default=0)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_report_links', to='forestal_bot.whatsappmessage')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='forestal_bot.fuelreport')),
            ],
            options={
                'db_table': 'forestal_bot_fuel_report_source_message',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='fgpydriver',
            constraint=models.CheckConstraint(condition=models.Q(('organization_key', 'forestal-paraguay')), name='forestal_fgpy_driver_org_check'),
        ),
        migrations.AddConstraint(
            model_name='fgpydriver',
            constraint=models.UniqueConstraint(condition=models.Q(('proposal_key', ''), _negated=True), fields=('organization_key', 'proposal_key'), name='forestal_fgpy_driver_proposal_uniq'),
        ),
        migrations.AddConstraint(
            model_name='fgpyvehicle',
            constraint=models.CheckConstraint(condition=models.Q(('organization_key', 'forestal-paraguay')), name='forestal_fgpy_vehicle_org_check'),
        ),
        migrations.AddConstraint(
            model_name='fgpyvehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed'), models.Q(('normalized_plate', ''), _negated=True)), fields=('organization_key', 'normalized_plate'), name='forestal_fgpy_vehicle_plate_confirmed_uniq'),
        ),
        migrations.AddConstraint(
            model_name='fgpyvehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('proposal_key', ''), _negated=True), fields=('organization_key', 'proposal_key'), name='forestal_fgpy_vehicle_proposal_uniq'),
        ),
        migrations.AddIndex(
            model_name='fuelreport',
            index=models.Index(fields=['organization_key', 'origin_group_key', 'status'], name='forestal_fuel_scope_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='fuelreport',
            constraint=models.UniqueConstraint(fields=('organization_key', 'origin_group_key', 'idempotency_key'), name='forestal_bot_fuel_report_idem_uniq'),
        ),
        migrations.AddConstraint(
            model_name='fuelreportevidence',
            constraint=models.UniqueConstraint(fields=('report', 'sha256'), name='forestal_bot_fuel_evidence_sha_uniq'),
        ),
        migrations.AddConstraint(
            model_name='fuelreportsourcemessage',
            constraint=models.UniqueConstraint(fields=('report', 'message'), name='forestal_bot_fuel_source_message_uniq'),
        ),
    ]
