# Generated by Django 5.1.1 on 2025-07-25 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(db_column='idmovil', primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=30)),
                ('detalle', models.CharField(blank=True, max_length=255, null=True)),
                ('ult_hr_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'db_table': 'moviles',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(db_column='idPersonal', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal',
            },
        ),
        migrations.CreateModel(
            name='RegistroProduccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UN', models.CharField(max_length=50)),
                ('operacion', models.CharField(max_length=50)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('equipo', models.CharField(max_length=50)),
                ('operador', models.CharField(max_length=50)),
                ('hr_inicio', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('hr_fin', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('m3', models.IntegerField(default=0)),
                ('tn_despachadas', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('produccion', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('unidad_produccion', models.CharField(blank=True, max_length=50, null=True)),
                ('hrs_no_operativas', models.DecimalField(db_column='hrs_no_op', decimal_places=2, default=0.0, max_digits=12)),
                ('plantas', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('combustible', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('aceite_cadena', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('predio', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_equipo', models.ForeignKey(db_column='cod_equipo', on_delete=django.db.models.deletion.CASCADE, to='produccion.equipo')),
            ],
            options={
                'db_table': 'tablero_produccion',
            },
        ),
    ]
