# Generated by Django 5.1.1 on 2025-07-25 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='user',
        ),
    ]
