# Generated by Django 5.1.1 on 2025-08-26 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0005_empleado_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LugarCarga',
            fields=[
                ('id', models.AutoField(db_column='idLugarCarga', primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'lugarcarga',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, unique=True)),
                ('simbolo', models.CharField(max_length=10, unique=True)),
                ('cambio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'moneda',
            },
        ),
        migrations.CreateModel(
            name='TipoMovil',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipodemovil',
            },
        ),
        migrations.CreateModel(
            name='UnidadNegocio',
            fields=[
                ('id', models.AutoField(db_column='idUnidadNegocio', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'unidadnegocio',
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='baja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='acta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='hr_disposicion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='motivo_no_op',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='observaciones',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='stock_abc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipo_movil',
            field=models.ForeignKey(blank=True, db_column='tipo_movil', null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.tipomovil'),
        ),
        migrations.CreateModel(
            name='ProduccionMensual',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=7)),
                ('tipo_operacion', models.CharField(blank=True, max_length=50, null=True)),
                ('produccion', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cantidad_equipo', models.IntegerField(default=0)),
                ('unidad_produccion', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad_negocio', models.ForeignKey(blank=True, db_column='un', null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.unidadnegocio')),
            ],
            options={
                'db_table': 'produccion_mensual',
            },
        ),
        migrations.CreateModel(
            name='Panioles',
            fields=[
                ('idPaniol', models.AutoField(db_column='idPaniol', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('un', models.ForeignKey(db_column='un', on_delete=django.db.models.deletion.CASCADE, to='produccion.unidadnegocio')),
            ],
            options={
                'db_table': 'panioles',
            },
        ),
        migrations.CreateModel(
            name='CargaCombustible',
            fields=[
                ('id', models.AutoField(db_column='idCargaComb', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('litros', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('km', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tipo_mov', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso')], default='I', max_length=1)),
                ('equipo', models.ForeignKey(db_column='idmovil', on_delete=django.db.models.deletion.CASCADE, to='produccion.equipo')),
                ('lugar_carga', models.ForeignKey(blank=True, db_column='idLugarCarga', null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.lugarcarga')),
                ('unidad_negocio', models.ForeignKey(blank=True, db_column='UnidadNegocio', null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.unidadnegocio')),
            ],
            options={
                'db_table': 'cargacomb',
            },
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='cod_un',
            field=models.ForeignKey(blank=True, db_column='cod_un', null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.unidadnegocio'),
        ),
    ]
