# Generated by Django 5.1.1 on 2026-07-10 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0009_merge_equipo_aliases_hr_remolque'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.AutoField(db_column='idOrigen', primary_key=True, serialize=False)),
                ('origen', models.CharField(db_column='ORIGEN', max_length=40)),
                ('destino', models.CharField(db_column='DESTINO', max_length=40)),
                ('kms', models.IntegerField(db_column='KMS', default=0)),
                ('precio', models.DecimalField(db_column='PRECIO', decimal_places=4, default=0.0, max_digits=12)),
                ('km_tierra', models.DecimalField(db_column='KMTIERRA', decimal_places=2, default=0.0, max_digits=12)),
                ('km_asfalto', models.DecimalField(db_column='KMASFALTO', decimal_places=2, default=0.0, max_digits=12)),
                ('precosecha', models.DecimalField(db_column='PRECOSECHA', decimal_places=4, default=0.0, max_digits=12)),
                ('codigo_destino', models.CharField(db_column='CodigoDestino', max_length=10)),
            ],
            options={
                'verbose_name': 'Origen',
                'verbose_name_plural': 'Origenes',
                'db_table': 'origen',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='produccionmensual',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='aceite_hidraulico',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='cadena',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='cantidad_cadenas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='espada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='giro_pinon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='pinon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='puntera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='remito_bitren',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='tarifa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='origen_camion',
            field=models.ForeignKey(blank=True, db_column='origen_camion', null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.origen'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=state_operations,
        )
    ]
