# Generated by Django 5.1.1 on 2026-07-11 12:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0011_registroproduccion_cod_operador_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_display', models.CharField(max_length=120)),
                ('alias_normalizado', models.CharField(db_index=True, max_length=120)),
                ('alias_activo_key', models.CharField(blank=True, editable=False, max_length=120, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('openclaw', 'OpenClaw'), ('importacion', 'Importación'), ('sistema', 'Sistema')], max_length=20)),
                ('confirmado_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('confirmado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipo_aliases_confirmados', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alias_records', to='produccion.equipo')),
            ],
            options={
                'db_table': 'equipo_alias',
                'ordering': ('alias_display', 'id'),
                'constraints': [models.UniqueConstraint(fields=('equipo', 'alias_normalizado'), name='equipo_alias_equipo_normalizado_uniq')],
            },
        ),
    ]
