# Generated by Django 5.1.1 on 2026-07-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    state_operations = [
        migrations.CreateModel(
            name='OrdenServicioCabecera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=20)),
                ('cerrado_por', models.CharField(max_length=30)),
                ('externo', models.BooleanField()),
                ('proveedor', models.IntegerField()),
                ('mecanico', models.IntegerField()),
                ('usuario', models.CharField(max_length=30)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cambio', models.FloatField()),
                ('orden_servicio', models.CharField(max_length=12)),
                ('planilla_trabajo', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Orden de Servicio Cabecera',
                'verbose_name_plural': 'Ordenes de Servicio Cabeceras',
                'db_table': 'cab_orden_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenServicioDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
                ('precio_unitario', models.FloatField()),
                ('preventivo', models.BooleanField()),
                ('correctivo', models.BooleanField()),
                ('realizado', models.BooleanField()),
                ('km_hora', models.FloatField()),
                ('diferencia', models.FloatField()),
                ('detalle', models.TextField()),
                ('fecha_realizacion', models.DateField(blank=True, null=True)),
                ('cambio', models.FloatField()),
                ('observaciones', models.CharField(max_length=200)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('horas_extras', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Orden de Servicio Detalle',
                'verbose_name_plural': 'Ordenes de Servicio Detalles',
                'db_table': 'det_orden_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Repuestos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
                ('stock_actual', models.IntegerField()),
                ('stock_minimo', models.IntegerField()),
                ('costo_unitario', models.FloatField()),
                ('fecha_actualizacion', models.DateField()),
                ('activo', models.BooleanField()),
                ('maneja_stock', models.BooleanField()),
                ('usuario', models.CharField(max_length=30)),
                ('codigo_interno', models.CharField(max_length=30)),
                ('creado', models.DateTimeField()),
                ('id_tango', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'repuestos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=80)),
                ('activo', models.BooleanField()),
                ('cantidad_empleados', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'db_table': 'sectores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTareas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tarea', models.CharField(max_length=150)),
                ('cada_cuanto', models.IntegerField()),
                ('anticipacion', models.IntegerField()),
                ('tipo_movil_id', models.IntegerField()),
                ('activo', models.BooleanField()),
                ('descripcion', models.TextField()),
                ('usuario', models.CharField(max_length=30)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Tarea',
                'verbose_name_plural': 'Tipos de Tareas',
                'db_table': 'tipostareas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidadmedida',
                'managed': False,
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=state_operations,
        )
    ]
