from django.urls import path

from forestal_bot.views import (
    DailySummaryDetailView,
    DailySummaryListCreateView,
    WhatsAppGroupDetailView,
    WhatsAppGroupListCreateView,
    WhatsAppMessageCreateView,
    WhatsAppMessageRecentView,
    WhatsAppOwnerMessageListView,
    WeighingMeasurementUpsertView,
    WeighingMovementCompleteView,
    WeighingMovementDetailView,
    WeighingMovementListCreateView,
    WeighingSummaryView,
)

app_name = "forestal_bot"

urlpatterns = [
    path(
        "weighing-movements/",
        WeighingMovementListCreateView.as_view(),
        name="weighing-movement-list",
    ),
    path(
        "weighing-movements/summary/",
        WeighingSummaryView.as_view(),
        name="weighing-summary",
    ),
    path(
        "weighing-movements/<uuid:pk>/",
        WeighingMovementDetailView.as_view(),
        name="weighing-movement-detail",
    ),
    path(
        "weighing-movements/<uuid:pk>/measurements/",
        WeighingMeasurementUpsertView.as_view(),
        name="weighing-measurement-upsert",
    ),
    path(
        "weighing-movements/<uuid:pk>/complete/",
        WeighingMovementCompleteView.as_view(),
        name="weighing-movement-complete",
    ),
    path(
        "daily-summaries/",
        DailySummaryListCreateView.as_view(),
        name="daily-summary-list",
    ),
    path(
        "daily-summaries/<int:pk>/",
        DailySummaryDetailView.as_view(),
        name="daily-summary-detail",
    ),
    path(
        "whatsapp/owner/messages/",
        WhatsAppOwnerMessageListView.as_view(),
        name="whatsapp-owner-message-list",
    ),
    path(
        "whatsapp/groups/",
        WhatsAppGroupListCreateView.as_view(),
        name="whatsapp-group-list",
    ),
    path(
        "whatsapp/groups/<int:pk>/",
        WhatsAppGroupDetailView.as_view(),
        name="whatsapp-group-detail",
    ),
    path(
        "whatsapp/messages/recent/",
        WhatsAppMessageRecentView.as_view(),
        name="whatsapp-message-recent",
    ),
    path(
        "whatsapp/messages/",
        WhatsAppMessageCreateView.as_view(),
        name="whatsapp-message-list",
    ),
]
